name: Unit Test
on:
  workflow_dispatch:
    inputs:
      test1: 
        required: false
        default: none
      test2:
        required: false
        default: none

jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3